---
# tasks file for ansible-jellyfin
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_os_family == "Debian"

- name: Ensure required packages are installed
  ansible.builtin.package:
    name:
      - gnupg
      - apt-transport-https
    state: present

- name: Add Jellyfin APT signing key
  ansible.builtin.apt_key:
    url: "{{ jellyfin_gpg_key }}"
    keyring: /etc/apt/keyrings/jellyfin.gpg
    state: present

- name: Add Jellyfin APT repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/jellyfin.sources
    owner: root
    group: root
    mode: "0644"
    content: |
      Types: deb
      URIs: https://repo.jellyfin.org/debian/
      Suites: trixie
      Components: main
      Signed-By: /etc/apt/keyrings/jellyfin.gpg

- name: Install Jellyfin
  ansible.builtin.apt:
    name: jellyfin
    state: present

- name: Ensure jellyfin service is enabled and started
  ansible.builtin.systemd:
    name: jellyfin
    state: started
    enabled: true
