---
# handlers file for ansible-jellyfin
- name: Restart jellyfin
  ansible.builtin.systemd:
    name: jellyfin
    state: restarted
    daemon_reload: true
  when: not jellyfin_is_test or jellyfin_is_test is undefined
