---
- name: Converge
  hosts: all

  roles:
    - role: ansible-jellyfin

    - role: tychobrouwer.lxc_mount
      lxc_mount_is_lxc: true
      lxc_mount_mounts:
        - { src: /media/file-share, dest: /share/file-share }
        - { src: /rpool-main/media-share, dest: /share/media-share }
      lxc_mount_lxc_id: 111
      lxc_mount_test_mode: true
      lxc_mount_users: [jellyfin]
